services:
  # S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  # Kafka-compatible broker (Redpanda) with OUTSIDE listener for host clients
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092,OUTSIDE://localhost:9094
      - --rpc-addr=0.0.0.0:33145
      - --advertise-rpc-addr=redpanda:33145
    ports:
      - "9092:9092"   # internal network clients
      - "9094:9094"   # host clients (your Python)
      - "9644:9644"   # admin

  # Web UI for Kafka/Redpanda
  redpanda-console:
    image: redpandadata/console:latest
    container_name: redpanda-console
    environment:
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      - redpanda
    ports:
      - "8088:8080"   # use 8088 on host to avoid conflicts

volumes:
  minio_data:

